---
sudo: required
# docker is required to run tests
services: docker

install:
  - bundle install

script:
  # run kitchen tests (destroy, create, converge, setup, verify and destroy)
  - bundle exec kitchen test

notifications:
  slack:
    secure: GnKONbx4q+Jld4YY66x5o3REviSj4fzsTznEHDmOiA5nVmfuV4TRk+FLXS93+jUVQpXFMs4SEweFIKA5pfW8arnMuq+2/noMCnWXQ7uSRvPAPREDtFASCa7ytZhzbX9y91R3D6iTUl9ZdMk41kcVsraJxI1vOPhwZ23o+euPwm4G4SpQ2bwBEPIqN5hZRyHqHrWX2fYR1EfHRJNdd61R4OyJaHgOjOPV2b8lussI0MH2JPHB7MT2vPy6YSle18sHjDdjxlXElh2GSuCGS/wnu1TdTFnv3q8+A7CfH84Ocoa06oNo2eCquQjKO0mJu0LcOWwQugydEhMlNyDEO7ncQKypMpVicoW1nwNB/zUC2CvK5rQYFdRBOsTWCP2IoMar36VTRk+i4Ob4TPRw4UAazNL8i2FqDomAu8uy+XAtr3H5LSyYQYL8+7G3zLhpEZyiVLm9vThrHQ/xamix+SH1QNYIBM3utY2rHjjIdhiOMlufyojy9ft5azIjt6feiFqvD/v+SL0/saY3sy/X7Kn2jqzAOz7LNPlkqet0t8zdbcJ7HbBX3FTjqvMCj32P+n7Ub3bOPtpBv9VqBKhUUMM3LLPdGb/Gy9EcJKqEjP15IcAPxp+TqntWYrDS9M7F2Mapej5IcZc1kr3/1mXpZZtgEscZR2qZqH9DXY7GvXU0kl4=
